# 統一多語言敏感詞檢測與替換系統配置文件
# Unified Multi-language Sensitive Word Detection and Replacement System Configuration

# 目錄配置
directories:
  input_dir: "i18n_input"           # 輸入目錄，包含各語言的原始檔案
  output_dir: "i18n_output"        # 輸出目錄，包含各語言的處理結果
  backup_dir: "backup"             # 備份目錄

# 檔案命名配置
file_patterns:
  po_file: "messages.po"           # PO 檔案名稱
  json_file: "{language}.json"    # JSON 檔案名稱模板，{language} 會被替換
  
  # 統一的對照表和待修正檔案
  phrase_comparison: "phrase_comparison.xlsx"     # 統一對照表
  tobemodified: "tobemodified_{language}.xlsx"   # 各語言的待修正清單
  
  # 新增：部分檔案命名模板
  partial_po: "messages{suffix}_partial.po"       # 部分 PO 檔案命名
  partial_json: "{language}{suffix}_partial.json" # 部分 JSON 檔案命名
  
  # 輸出目錄命名（含時間戳）
  output_subdir: "{language}_{timestamp}"
  partial_output_subdir: "{language}_{timestamp}_partial"  # 部分檔案輸出目錄

# 業態配置
business_types:
  enterprises:
    suffix: "_enterprises"
    display_name: "企業"
    description: "企業客戶適用的敏感詞解決方案"
  
  public_sector:
    suffix: "_public_sector"
    display_name: "公部門"
    description: "政府機關與公部門適用的敏感詞解決方案"
  
  training_institutions:
    suffix: "_training_institutions" 
    display_name: "培訓機構"
    description: "教育訓練機構適用的敏感詞解決方案"

# 檔案處理規則
file_handling:
  # 檔案路徑配置：JSON 在語言根目錄，PO 在 LC_MESSAGES 子目錄
  json_in_root: true               # JSON 檔案在語言根目錄
  po_in_lc_messages: true          # PO 檔案在 LC_MESSAGES 子目錄
  lc_messages_subdir: "LC_MESSAGES"  # LC_MESSAGES 子目錄名稱
  
  # 檔案優先順序和處理規則
  priority_files: ["messages.po", "{language}.json"]
  ignore_patterns: ["*.tmp", "*.bak", "*.log", "*~"]
  require_at_least_one: true  # 至少需要一個優先檔案存在
  # 新增：如果兩個檔案都存在，優先處理哪個（如果有衝突的話）
  file_priority: "both"  # both: 都處理, po: 優先PO, json: 優先JSON

# 統一 Excel 配置
excel_config:
  # 工作表配置
  worksheets:
    comparison: "phrase_comparison"   # 對照表工作表名稱
    summary: "語言總覽"               # 總覽工作表名稱
  
  # 佈局模式：horizontal (橫向分區塊)
  layout_mode: "horizontal"
  
  # 橫向分區塊配置
  horizontal_layout:
    use_language_blocks: true        # 使用語言區塊分區
    block_separator_columns: 1       # 語言區塊間的分隔列數
    language_independent: true       # 語言獨立模式：每個語言有自己的敏感詞
    language_label_style: "header"   # 語言標籤樣式：header/merged/simple
    allow_user_additions: true      # 允許用戶在區塊內新增詞彙
    error_tolerance: "high"          # 錯誤容忍度：high/medium/low
    
    # 語言獨立區塊結構
    block_structure:
      category_column: true          # 每個區塊包含敏感詞類型列
      keyword_column: true           # 每個區塊包含敏感詞列
      business_columns: true         # 每個區塊包含業態方案列
  
  # 必要欄位（基礎部分）
  required_columns:
    category: "敏感詞類型"
    keyword: "敏感詞"
  
  # 業態方案欄位模板（橫向模式）
  business_columns:
    # 橫向模式的列名模板：{language}_{business_display_name}
    horizontal_template: "{language}_{business_display_name}"
    # 用於解析的模板
    parse_pattern: r"^(.+?)_(.+)$"  # 用於解析 語言_業態 格式
  
  # 樣式設定
  styling:
    language_header_color: "4472C4"  # 語言標題背景色
    category_header_color: "70AD47"  # 分類標題背景色
    data_row_color: "F2F2F2"        # 奇數行背景色
    business_header_color: "FFC000"  # 業態標題背景色
    language_block_border: "thick"   # 語言區塊邊框樣式

# 語言檢測配置
language_detection:
  # 檔案檢測優先順序
  file_priority:
    - "messages.po"
    - "{language}.json"
  
  # 大小寫處理
  case_handling:
    ignore_case: true              # 忽略檔案名大小寫
    
  # 檔案驗證
  validation:
    require_at_least_one: true     # 至少需要一個檔案
    warn_missing_files: true      # 警告缺失的檔案

# 敏感詞檢測設定
keyword_detection:
  case_sensitive: false
  match_whole_words: false
  priority_by_length: true         # 優先匹配長詞
  
  # 包容關係處理配置
  inclusion_handling:
    enabled: true                  # 啟用包容關係檢測
    cross_category: true           # 跨分類檢測包容關係
    debug_output: true             # 顯示包容關係分析結果
    add_position_column: false      # 在Excel中添加匹配位置欄位
    
  # 基礎敏感詞配置
  base_keywords:
    use_builtin: true              # 使用內建基礎詞典
    extract_from_files: true      # 從檔案中提取敏感詞
    merge_strategies: "union"      # 合併策略：union/intersection

# 備份設定
backup:
  timestamp_format: "%Y%m%d_%H%M%S"
  auto_backup: true               # 自動備份現有檔案
  keep_original: true
  log_operations: true

# 輸出設定
output:
  # 輸出檔案命名模板
  file_templates:
    po: "{base_name}{suffix}.po"
    json: "{base_name}{suffix}.json"
    # 新增：部分檔案模板
    partial_po: "{base_name}{suffix}_partial.po"
    partial_json: "{base_name}{suffix}_partial.json"
  
  # 目錄結構
  create_timestamped_dirs: true   # 創建帶時間戳的輸出目錄
  preserve_structure: true       # 保持原始檔案結構
  
  # 新增：部分檔案配置
  partial_files:
    enabled: true                 # 啟用部分檔案功能
    include_metadata: true        # 在部分檔案中包含元信息
    preserve_comments: true       # 保留原檔案的註解
    add_generation_info: true     # 添加生成信息到檔案中

# 新增：部分檔案處理配置
partial_file_handling:
  # PO 檔案配置
  po_files:
    preserve_metadata: true       # 保留 PO 檔案元信息
    preserve_header: true         # 保留 PO 檔案標題
    preserve_comments: true       # 保留註解
    preserve_flags: true          # 保留標誌
    preserve_occurrences: true    # 保留出現位置信息
    add_processing_comments: true # 添加處理信息到註解
  
  # JSON 檔案配置
  json_files:
    add_metadata: true            # 添加元信息到 JSON
    preserve_structure: true      # 保持 JSON 結構
    indent: 2                     # JSON 縮排空格數
    ensure_ascii: false           # 允許非 ASCII 字符
    sort_keys: false              # 不排序鍵值
  
  # 輸出配置
  output:
    create_separate_dirs: true    # 為部分檔案創建獨立目錄
    add_timestamp: true           # 在目錄名中添加時間戳
    include_summary: true         # 生成處理摘要

# 系統設定
system:
  # 日誌設定
  logging:
    level: "INFO"
    include_timestamps: true
    log_file_pattern: "{operation}_{timestamp}.log"
  
  # 處理設定
  processing:
    validate_before_processing: true
    continue_on_errors: false
    show_progress: true

# 版本資訊
version: "2.6.0"
last_updated: "2024-12-10"
system_type: "unified_multi_language_excel_with_partial_files"

# 預設值
defaults:
  language: null                  # 無預設語言，自動檢測
  business_type: "enterprises"    # 預設業態
  backup_before_overwrite: true

# 新增：檔案合併配置
combine:
  # 合併來源目錄 - 固定為 i18n_combine
  combine_dir: "i18n_combine"
  
  # 合併輸出配置
  output:
    create_timestamped_dirs: true     # 創建帶時間戳的輸出目錄
    directory_suffix: "_combined"     # 輸出目錄後綴
    preserve_original_structure: true # 保持原始檔案結構
    file_suffix: "_combined"          # 合併檔案後綴
  
  # 衝突處理配置
  conflict_handling:
    stop_on_conflict: true            # 發現衝突時停止處理
    show_conflict_details: true       # 顯示衝突詳情
    max_conflicts_to_show: 10         # 最多顯示的衝突數量
    log_all_conflicts: true           # 將所有衝突記錄到日誌
  
  # 檔案驗證配置
  validation:
    check_file_existence: true        # 檢查目標檔案是否存在
    validate_json_format: true        # 驗證 JSON 檔案格式
    validate_po_format: true          # 驗證 PO 檔案格式
    warn_missing_target_files: true   # 警告缺失的目標檔案
  
  # 合併策略配置
  merge_strategy:
    skip_identical_values: true       # 跳過相同的值
    case_sensitive_comparison: true   # 大小寫敏感的比較
    trim_whitespace: true             # 比較前去除空白字符
    handle_empty_values: "skip"       # 處理空值：skip/error/warn
    auto_detect_business_types: true  # 自動檢測有替換結果的業態
  
  # 日誌配置
  logging:
    detailed_merge_log: true          # 詳細的合併日誌
    include_skipped_items: false      # 包含跳過的項目在日誌中
    include_debug_info: true          # 包含調試信息
    log_file_pattern: "combine_{timestamp}.log"

# 在現有的檔案命名配置中添加
file_patterns:
  # ... 現有配置 ...
  
  # 新增：合併相關檔案命名
  combine_output: "{language}_{timestamp}_combined"      # 合併輸出目錄命名
  combine_summary: "combine_summary_{timestamp}.txt"     # 合併摘要報告
  combine_log: "combine_{timestamp}.log"                 # 合併日誌檔案
  combine_po_suffix: "_combined"                          # 合併 PO 檔案後綴
  combine_json_suffix: "_combined"                        # 合併 JSON 檔案後綴