# 多語言敏感詞檢測與替換系統配置文件
# Multi-language Sensitive Word Detection and Replacement System Configuration

# 目錄配置
directories:
  input_dir: "i18n_input"           # 輸入目錄，包含各語言的原始檔案
  output_dir: "i18n_output"        # 輸出目錄，包含各語言的處理結果
  backup_dir: "backup"             # 備份目錄

# 檔案命名配置
file_patterns:
  po_file: "messages.po"           # PO 檔案名稱
  json_file: "{language}.json"    # JSON 檔案名稱模板，{language} 會被替換
  
  # 輸出檔案命名
  phrase_comparison: "phrase_comparison_{language}.xlsx"
  tobemodified: "tobemodified_{language}.xlsx"
  
  # 輸出目錄命名（含時間戳）
  output_subdir: "{language}_{timestamp}"

# 業態配置
business_types:
  enterprises:
    suffix: "_enterprises"
    display_name: "企業"
    description: "企業客戶適用的敏感詞解決方案"
  
  public_sector:
    suffix: "_public_sector"
    display_name: "公部門"
    description: "政府機關與公部門適用的敏感詞解決方案"
  
  training_institutions:
    suffix: "_training_institutions" 
    display_name: "培訓機構"
    description: "教育訓練機構適用的敏感詞解決方案"

# Excel 配置
excel_config:
  # 必要欄位
  required_columns:
    category: "敏感詞類型"
    keyword: "敏感詞"
  
  # 業態方案欄位模板
  business_columns:
    solution_template: "對應方案({display_name})"
  
  # Excel 檔案設定
  worksheet_name: "phrase_comparison"
  header_row: 1
  data_start_row: 2

# 語言檢測配置
language_detection:
  # 檔案檢測優先順序
  file_priority:
    - "messages.po"
    - "{language}.json"
  
  # 大小寫處理
  case_handling:
    ignore_case: true              # 忽略檔案名大小寫
    
  # 檔案驗證
  validation:
    require_at_least_one: true     # 至少需要一個檔案
    warn_missing_files: true      # 警告缺失的檔案

# 敏感詞檢測設定
keyword_detection:
  case_sensitive: false
  match_whole_words: false
  priority_by_length: true         # 優先匹配長詞
  
  # 跨語言合併設定
  cross_language:
    merge_categories: true         # 合併相同分類名稱
    deduplicate_keywords: true    # 去除重複敏感詞

# 備份設定
backup:
  timestamp_format: "%Y%m%d_%H%M%S"
  auto_backup: true               # 自動備份現有檔案
  keep_original: true
  log_operations: true

# 輸出設定
output:
  # 輸出檔案命名模板
  file_templates:
    po: "{base_name}{suffix}.po"
    json: "{base_name}{suffix}.json"
  
  # 目錄結構
  create_timestamped_dirs: true   # 創建帶時間戳的輸出目錄
  preserve_structure: true       # 保持原始檔案結構

# 系統設定
system:
  # 日誌設定
  logging:
    level: "INFO"
    include_timestamps: true
    log_file_pattern: "{operation}_{timestamp}.log"
  
  # 處理設定
  processing:
    validate_before_processing: true
    continue_on_errors: false
    show_progress: true

# 版本資訊
version: "2.2.0"
last_updated: "2024-12-10"
system_type: "multi_language_excel"

# 預設值
defaults:
  language: null                  # 無預設語言，自動檢測
  business_type: "enterprises"    # 預設業態
  backup_before_overwrite: true