# 統一多語言敏感詞檢測與替換系統配置文件
# Unified Multi-language Sensitive Word Detection and Replacement System Configuration

# 目錄配置
directories:
  input_dir: "i18n_input"           # 輸入目錄，包含各語言的原始檔案
  output_dir: "i18n_output"        # 輸出目錄，包含各語言的處理結果
  backup_dir: "backup"             # 備份目錄

# 檔案命名配置
file_patterns:
  po_file: "messages.po"           # PO 檔案名稱
  json_file: "{language}.json"    # JSON 檔案名稱模板，{language} 會被替換
  
  # 統一的對照表和待修正檔案
  phrase_comparison: "phrase_comparison.xlsx"     # 統一對照表
  tobemodified: "tobemodified_{language}.xlsx"   # 各語言的待修正清單
  
  # 輸出目錄命名（含時間戳）
  output_subdir: "{language}_{timestamp}"

# 業態配置
business_types:
  enterprises:
    suffix: "_enterprises"
    display_name: "企業"
    description: "企業客戶適用的敏感詞解決方案"
  
  public_sector:
    suffix: "_public_sector"
    display_name: "公部門"
    description: "政府機關與公部門適用的敏感詞解決方案"
  
  training_institutions:
    suffix: "_training_institutions" 
    display_name: "培訓機構"
    description: "教育訓練機構適用的敏感詞解決方案"

# 檔案處理規則
file_handling:
  # 檔案路徑配置：JSON 在語言根目錄，PO 在 LC_MESSAGES 子目錄
  json_in_root: true               # JSON 檔案在語言根目錄
  po_in_lc_messages: true          # PO 檔案在 LC_MESSAGES 子目錄
  lc_messages_subdir: "LC_MESSAGES"  # LC_MESSAGES 子目錄名稱
  
  # 檔案優先順序和處理規則
  priority_files: ["messages.po", "{language}.json"]
  ignore_patterns: ["*.tmp", "*.bak", "*.log", "*~"]
  require_at_least_one: true  # 至少需要一個優先檔案存在
  # 新增：如果兩個檔案都存在，優先處理哪個（如果有衝突的話）
  file_priority: "both"  # both: 都處理, po: 優先PO, json: 優先JSON

# 統一 Excel 配置
excel_config:
  # 工作表配置
  worksheets:
    comparison: "phrase_comparison"   # 對照表工作表名稱
    summary: "語言總覽"               # 總覽工作表名稱
  
  # 必要欄位
  required_columns:
    language: "語言"
    category: "敏感詞類型"
    keyword: "敏感詞"
  
  # 業態方案欄位模板
  business_columns:
    solution_template: "對應方案({display_name})"
  
  # 語言區塊設定
  language_blocks:
    header_rows: 2                  # 每個語言區塊的標題行數
    separator_rows: 1               # 語言區塊間的分隔行數
    start_row: 3                    # 數據開始行（跳過總標題）
  
  # 樣式設定
  styling:
    language_header_color: "366092"  # 語言標題背景色
    category_header_color: "70AD47"  # 分類標題背景色
    data_row_color: "F2F2F2"        # 奇數行背景色

# 語言檢測配置
language_detection:
  # 檔案檢測優先順序
  file_priority:
    - "messages.po"
    - "{language}.json"
  
  # 大小寫處理
  case_handling:
    ignore_case: true              # 忽略檔案名大小寫
    
  # 檔案驗證
  validation:
    require_at_least_one: true     # 至少需要一個檔案
    warn_missing_files: true      # 警告缺失的檔案

# 敏感詞檢測設定
keyword_detection:
  case_sensitive: false
  match_whole_words: false
  priority_by_length: true         # 優先匹配長詞
  
  # 基礎敏感詞配置
  base_keywords:
    use_builtin: true              # 使用內建基礎詞典
    extract_from_files: true      # 從檔案中提取敏感詞
    merge_strategies: "union"      # 合併策略：union/intersection

# 備份設定
backup:
  timestamp_format: "%Y%m%d_%H%M%S"
  auto_backup: true               # 自動備份現有檔案
  keep_original: true
  log_operations: true

# 輸出設定
output:
  # 輸出檔案命名模板
  file_templates:
    po: "{base_name}{suffix}.po"
    json: "{base_name}{suffix}.json"
  
  # 目錄結構
  create_timestamped_dirs: true   # 創建帶時間戳的輸出目錄
  preserve_structure: true       # 保持原始檔案結構

# 系統設定
system:
  # 日誌設定
  logging:
    level: "INFO"
    include_timestamps: true
    log_file_pattern: "{operation}_{timestamp}.log"
  
  # 處理設定
  processing:
    validate_before_processing: true
    continue_on_errors: false
    show_progress: true

# 版本資訊
version: "2.3.0"
last_updated: "2024-12-10"
system_type: "unified_multi_language_excel"

# 預設值
defaults:
  language: null                  # 無預設語言，自動檢測
  business_type: "enterprises"    # 預設業態
  backup_before_overwrite: true