# 敏感詞檢測與替換系統配置文件 (純 Excel 版本)
# Configuration for Sensitive Word Detection and Replacement System (Excel-Only Version)

# 語言配置
languages:
  zh-TW:
    po_file: "messages.po"
    json_file: "zh-TW.json"
    description: "繁體中文"
  # 可擴充其他語言
  # en:
  #   po_file: "messages_en.po" 
  #   json_file: "en.json"
  #   description: "English"

# 業態配置 (可擴充)
business_types:
  enterprises:
    suffix: "_enterprises"
    display_name: "企業"
    description: "企業客戶適用的敏感詞解決方案"
  
  public_sector:
    suffix: "_public_sector"
    display_name: "公部門"
    description: "政府機關與公部門適用的敏感詞解決方案"
  
  training_institutions:
    suffix: "_training_institutions" 
    display_name: "培訓機構"
    description: "教育訓練機構適用的敏感詞解決方案"
  
  # 可擴充其他業態
  # healthcare:
  #   suffix: "_healthcare"
  #   display_name: "醫療機構"
  #   description: "醫療保健機構適用的敏感詞解決方案"

# 基礎檔案配置 (純 Excel 版本)
base_files:
  # 唯一的數據源：Excel 檔案
  phrase_comparison_excel: "phrase_comparison.xlsx"
  output_dir: "."
  backup_dir: "backup"

# Excel 檔案配置
excel_config:
  # 必要欄位
  required_columns:
    category: "敏感詞類型"
    keyword: "敏感詞"
  
  # 業態方案欄位模板
  business_columns:
    solution_template: "對應方案({display_name})"
    validation_template: "一對多校驗({display_name})"
  
  # Excel 檔案設定
  worksheet_name: "phrase_comparison"
  header_row: 1
  data_start_row: 2

# 檔案生成配置
file_generation:
  # tobemodified Excel 檔案
  tobemodified_template: "tobemodified_{language}.xlsx"
  
  # 輸出檔案命名
  output_files:
    po_template: "{base_name}{suffix}.po"
    json_template: "{base_name}{suffix}.json"

# 系統設定
system:
  # 關鍵字檢測設定
  keyword_detection:
    case_sensitive: false
    match_whole_words: false
    priority_by_length: true  # 優先匹配長詞
  
  # 備份設定
  backup:
    timestamp_format: "%Y%m%d_%H%M%S"
    keep_original: true
    log_operations: true

# 預設語言 (當未指定時使用)
default_language: "zh-TW"

# 版本資訊
version: "2.1.0"
last_updated: "2024-12-10"
system_type: "excel_only"  # 標記為純 Excel 系統